# SonarQube properties for ireclamationfront (Angular frontend)
sonar.projectKey=ireclamationfront
sonar.projectName=ireclamationfront
sonar.host.url=http://192.168.1.31:9000
sonar.sources=src
sonar.language=ts
# Uncomment and set if you use tests
# sonar.tests=src/app/__tests__
