// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using iReclamation;

#nullable disable

namespace iReclamation.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("iReclamation.Models.Actions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Actions");
                });

            modelBuilder.Entity("iReclamation.Models.Adherent", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Adresse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Affiliation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Codeimmatriculation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Dateaffiliation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Datenaissance")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Daterecrutement")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Immatriculation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numppr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Organisme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RegionId")
                        .HasColumnType("int");

                    b.Property<string>("Sexe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Situationfamiliale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Statutadherent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VilleId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("RegionId");

                    b.HasIndex("VilleId");

                    b.ToTable("Adherent");
                });

            modelBuilder.Entity("iReclamation.Models.Dashboard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dashboard");
                });

            modelBuilder.Entity("iReclamation.Models.Dossier", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("Annee_dossier")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("datetime2");

                    b.Property<int>("EtatDossierId")
                        .HasColumnType("int");

                    b.Property<int>("Numero_dossier")
                        .HasColumnType("int");

                    b.Property<int>("ReclamationsId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("EtatDossierId");

                    b.HasIndex("ReclamationsId");

                    b.ToTable("Dossier");
                });

            modelBuilder.Entity("iReclamation.Models.EtatDossier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LibelleAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LibelleFr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EtatDossier");
                });

            modelBuilder.Entity("iReclamation.Models.EtatReclamation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LibelleAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EtatReclamations");
                });

            modelBuilder.Entity("iReclamation.Models.File", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReclamationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReclamationId")
                        .IsUnique();

                    b.ToTable("Files");
                });

            modelBuilder.Entity("iReclamation.Models.HistoriqueReclamation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateDeffet")
                        .HasColumnType("datetime2");

                    b.Property<string>("Etat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReclamationsId")
                        .HasColumnType("int");

                    b.Property<string>("Reponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("serviceId")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActionId");

                    b.HasIndex("ReclamationsId");

                    b.HasIndex("userId");

                    b.ToTable("HistoriqueReclamation");
                });

            modelBuilder.Entity("iReclamation.Models.Reclamations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdherentId")
                        .HasColumnType("int");

                    b.Property<string>("AdresseAdherent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdresseOrg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateBOinp")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateCloture")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateReception")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destinataire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EtatReclamationId")
                        .HasColumnType("int");

                    b.Property<string>("NomAdherent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Organisme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrenomAdherent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceBo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionAdherent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ServicesId")
                        .HasColumnType("int");

                    b.Property<int>("SourcesId")
                        .HasColumnType("int");

                    b.Property<int>("TypeReclamationsId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<bool?>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("treatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("villeAdherent")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdherentId");

                    b.HasIndex("EtatReclamationId");

                    b.HasIndex("ServicesId");

                    b.HasIndex("SourcesId");

                    b.HasIndex("TypeReclamationsId");

                    b.HasIndex("UserId");

                    b.ToTable("Reclamations");
                });

            modelBuilder.Entity("iReclamation.Models.Regions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("iReclamation.Models.Roles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("iReclamation.Models.Services", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LibelleAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("iReclamation.Models.Sources", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LibelleAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sources");
                });

            modelBuilder.Entity("iReclamation.Models.TypeReclamations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LibelleAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TypeReclamations");
                });

            modelBuilder.Entity("iReclamation.Models.UserDashboard", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int>("DashboardId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserDashboard");
                });

            modelBuilder.Entity("iReclamation.Models.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActif")
                        .HasColumnType("bit");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Prenom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RolesId")
                        .HasColumnType("int");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("RolesId");

                    b.HasIndex("ServiceId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("iReclamation.Models.Villes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LibelleAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RegionsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegionsId");

                    b.ToTable("Villes");
                });

            modelBuilder.Entity("iReclamation.Models.Adherent", b =>
                {
                    b.HasOne("iReclamation.Models.Regions", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId");

                    b.HasOne("iReclamation.Models.Villes", "Ville")
                        .WithMany()
                        .HasForeignKey("VilleId");

                    b.Navigation("Region");

                    b.Navigation("Ville");
                });

            modelBuilder.Entity("iReclamation.Models.Dossier", b =>
                {
                    b.HasOne("iReclamation.Models.EtatDossier", "EtatDossier")
                        .WithMany()
                        .HasForeignKey("EtatDossierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("iReclamation.Models.Reclamations", "Reclamations")
                        .WithMany("Dossiers")
                        .HasForeignKey("ReclamationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EtatDossier");

                    b.Navigation("Reclamations");
                });

            modelBuilder.Entity("iReclamation.Models.File", b =>
                {
                    b.HasOne("iReclamation.Models.Reclamations", "Reclamation")
                        .WithOne("File")
                        .HasForeignKey("iReclamation.Models.File", "ReclamationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reclamation");
                });

            modelBuilder.Entity("iReclamation.Models.HistoriqueReclamation", b =>
                {
                    b.HasOne("iReclamation.Models.Actions", "Action")
                        .WithMany()
                        .HasForeignKey("ActionId");

                    b.HasOne("iReclamation.Models.Reclamations", null)
                        .WithMany("HistoriqueReclamation")
                        .HasForeignKey("ReclamationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("iReclamation.Models.Users", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("user");
                });

            modelBuilder.Entity("iReclamation.Models.Reclamations", b =>
                {
                    b.HasOne("iReclamation.Models.Adherent", "Adherent")
                        .WithMany()
                        .HasForeignKey("AdherentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("iReclamation.Models.EtatReclamation", "EtatReclamation")
                        .WithMany()
                        .HasForeignKey("EtatReclamationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("iReclamation.Models.Services", "Services")
                        .WithMany("Reclamations")
                        .HasForeignKey("ServicesId");

                    b.HasOne("iReclamation.Models.Sources", "Sources")
                        .WithMany("Reclamations")
                        .HasForeignKey("SourcesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("iReclamation.Models.TypeReclamations", "TypeReclamations")
                        .WithMany("Reclamations")
                        .HasForeignKey("TypeReclamationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("iReclamation.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Adherent");

                    b.Navigation("EtatReclamation");

                    b.Navigation("Services");

                    b.Navigation("Sources");

                    b.Navigation("TypeReclamations");

                    b.Navigation("User");
                });

            modelBuilder.Entity("iReclamation.Models.UserDashboard", b =>
                {
                    b.HasOne("iReclamation.Models.Users", "User")
                        .WithMany("UserDashboards")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("iReclamation.Models.Users", b =>
                {
                    b.HasOne("iReclamation.Models.Roles", "Roles")
                        .WithMany()
                        .HasForeignKey("RolesId");

                    b.HasOne("iReclamation.Models.Services", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId");

                    b.Navigation("Roles");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("iReclamation.Models.Villes", b =>
                {
                    b.HasOne("iReclamation.Models.Regions", null)
                        .WithMany("Villes")
                        .HasForeignKey("RegionsId");
                });

            modelBuilder.Entity("iReclamation.Models.Reclamations", b =>
                {
                    b.Navigation("Dossiers");

                    b.Navigation("File");

                    b.Navigation("HistoriqueReclamation");
                });

            modelBuilder.Entity("iReclamation.Models.Regions", b =>
                {
                    b.Navigation("Villes");
                });

            modelBuilder.Entity("iReclamation.Models.Services", b =>
                {
                    b.Navigation("Reclamations");
                });

            modelBuilder.Entity("iReclamation.Models.Sources", b =>
                {
                    b.Navigation("Reclamations");
                });

            modelBuilder.Entity("iReclamation.Models.TypeReclamations", b =>
                {
                    b.Navigation("Reclamations");
                });

            modelBuilder.Entity("iReclamation.Models.Users", b =>
                {
                    b.Navigation("UserDashboards");
                });
#pragma warning restore 612, 618
        }
    }
}
